#!/bin/bash
# Alternative pour créer les comptes via l'interface Supabase SQL Editor

echo "🚀 Création des comptes de démonstration pour Teranga Foncier"
echo ""
echo "📋 Instructions pour Supabase Dashboard:"
echo ""
echo "1. Va sur https://supabase.com/dashboard"
echo "2. Sélectionne ton projet Teranga Foncier"
echo "3. Va dans 'SQL Editor'"
echo "4. Crée une nouvelle requête"
echo "5. Copie-colle le contenu du fichier: create-all-demo-accounts.sql"
echo "6. Exécute la requête"
echo ""
echo "🔑 Comptes qui seront créés (mot de passe: demo123):"
echo "  • admin@terangafoncier.com"
echo "  • particulier@terangafoncier.com"
echo "  • vendeur@terangafoncier.com"
echo "  • investisseur@terangafoncier.com"
echo "  • municipalite@terangafoncier.com"
echo "  • notaire@terangafoncier.com"
echo "  • geometre@terangafoncier.com"
echo "  • banque@terangafoncier.com"
echo "  • promoteur@terangafoncier.com"
echo ""
echo "🎯 Une fois terminé:"
echo "  • Teste sur: https://terangafoncier.vercel.app/"
echo "  • Consulte: GUIDE_TEST_PLATFORM.md"
echo ""
echo "✅ Prêt pour les tests!"
