# ======================================================================
# CRÉATION MANUELLE DES COMPTES POUR LES RÔLES RESTANTS
# Alternative sans API - Génération des scripts SQL
# ======================================================================

Write-Host "🔧 CRÉATION DES SCRIPTS SQL POUR LES COMPTES RESTANTS" -ForegroundColor Green
Write-Host "=====================================================" -ForegroundColor Yellow

# Générer le script SQL pour créer les comptes directement en base
$sqlScript = @"
-- ======================================================================
-- CRÉATION DES COMPTES POUR LES RÔLES RESTANTS
-- Script SQL à exécuter directement sur Supabase
-- ======================================================================

-- 1. PARTICULIERS (2 comptes)
INSERT INTO auth.users (
    instance_id, id, aud, role, email, encrypted_password, 
    email_confirmed_at, confirmation_sent_at, confirmation_token,
    recovery_sent_at, recovery_token, email_change_token_new, 
    email_change, email_change_token_current, email_change_confirm_status,
    banned_until, phone, phone_confirmed_at, phone_change, phone_change_token,
    phone_change_sent_at, confirmed_at, email_change_sent_at,
    email_change_token_current_segment, email_change_token_new_segment,
    is_super_admin, created_at, updated_at, raw_app_meta_data, raw_user_meta_data
) VALUES 
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'family.diallo@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 77 123 45 01',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Famille Diallo","role":"particulier","phone":"+221 77 123 45 01","organization":"Famille Diallo"}'::jsonb
),
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'ahmadou.ba@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 77 123 45 02',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Ahmadou Ba","role":"particulier","phone":"+221 77 123 45 02","organization":"Particulier"}'::jsonb
),

-- 2. VENDEURS (2 comptes)
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'heritage.fall@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 77 123 45 03',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Héritage Fall","role":"vendeur","phone":"+221 77 123 45 03","organization":"Succession Fall"}'::jsonb
),
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'domaine.seck@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 77 123 45 04',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Domaine Seck","role":"vendeur","phone":"+221 77 123 45 04","organization":"Propriété Familiale Seck"}'::jsonb
),

-- 3. PROMOTEURS (2 comptes)
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'urban.developers@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 33 123 45 05',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Urban Developers Sénégal","role":"promoteur","phone":"+221 33 123 45 05","organization":"Urban Developers"}'::jsonb
),
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'sahel.construction@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 33 123 45 06',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Sahel Construction","role":"promoteur","phone":"+221 33 123 45 06","organization":"Sahel Construction SARL"}'::jsonb
),

-- 4. BANQUES (2 comptes)
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'financement.boa@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 33 123 45 07',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"BOA Sénégal - Financement","role":"banque","phone":"+221 33 123 45 07","organization":"Bank of Africa Sénégal"}'::jsonb
),
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'credit.agricole@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 33 123 45 08',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Crédit Agricole Sénégal","role":"banque","phone":"+221 33 123 45 08","organization":"Crédit Agricole du Sénégal"}'::jsonb
),

-- 5. NOTAIRES (2 comptes)
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'etude.diouf@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 33 123 45 09',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Étude Notariale Diouf","role":"notaire","phone":"+221 33 123 45 09","organization":"Étude Me Diouf"}'::jsonb
),
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'chambre.notaires@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 33 123 45 10',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Chambre des Notaires","role":"notaire","phone":"+221 33 123 45 10","organization":"Chambre Régionale des Notaires"}'::jsonb
),

-- 6. AGENTS FONCIERS (2 comptes)
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'foncier.expert@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 77 123 45 11',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Foncier Expert Conseil","role":"agent_foncier","phone":"+221 77 123 45 11","organization":"Cabinet Foncier Expert"}'::jsonb
),
(
    '00000000-0000-0000-0000-000000000000',
    gen_random_uuid(),
    'authenticated',
    'authenticated',
    'teranga.immobilier@teranga-foncier.sn',
    crypt('password123', gen_salt('bf')),
    NOW(),
    NOW(),
    '',
    NULL,
    '',
    '',
    '',
    '',
    0,
    NULL,
    '+221 77 123 45 12',
    NULL,
    '',
    '',
    NULL,
    NOW(),
    NULL,
    '',
    '',
    FALSE,
    NOW(),
    NOW(),
    '{"provider":"email","providers":["email"]}',
    '{"full_name":"Teranga Immobilier","role":"agent_foncier","phone":"+221 77 123 45 12","organization":"Agence Teranga Immobilier"}'::jsonb
);

-- Vérification des comptes créés
SELECT 
    '✅ VÉRIFICATION DES NOUVEAUX COMPTES' as titre,
    email,
    raw_user_meta_data->>'full_name' as nom,
    raw_user_meta_data->>'role' as role,
    'CRÉÉ' as statut
FROM auth.users 
WHERE email IN (
    'family.diallo@teranga-foncier.sn',
    'ahmadou.ba@teranga-foncier.sn',
    'heritage.fall@teranga-foncier.sn',
    'domaine.seck@teranga-foncier.sn',
    'urban.developers@teranga-foncier.sn',
    'sahel.construction@teranga-foncier.sn',
    'financement.boa@teranga-foncier.sn',
    'credit.agricole@teranga-foncier.sn',
    'etude.diouf@teranga-foncier.sn',
    'chambre.notaires@teranga-foncier.sn',
    'foncier.expert@teranga-foncier.sn',
    'teranga.immobilier@teranga-foncier.sn'
)
ORDER BY raw_user_meta_data->>'role', email;

-- Résumé final
SELECT 
    '📊 RÉSUMÉ FINAL' as section,
    COUNT(*) || ' comptes créés' as resultat
FROM auth.users 
WHERE email IN (
    'family.diallo@teranga-foncier.sn',
    'ahmadou.ba@teranga-foncier.sn',
    'heritage.fall@teranga-foncier.sn',
    'domaine.seck@teranga-foncier.sn',
    'urban.developers@teranga-foncier.sn',
    'sahel.construction@teranga-foncier.sn',
    'financement.boa@teranga-foncier.sn',
    'credit.agricole@teranga-foncier.sn',
    'etude.diouf@teranga-foncier.sn',
    'chambre.notaires@teranga-foncier.sn',
    'foncier.expert@teranga-foncier.sn',
    'teranga.immobilier@teranga-foncier.sn'
);
"@

# Écrire le script SQL dans un fichier
$sqlScript | Out-File -FilePath "create-remaining-accounts.sql" -Encoding UTF8

Write-Host "✅ Script SQL généré: create-remaining-accounts.sql" -ForegroundColor Green
Write-Host ""
Write-Host "📋 COMPTES À CRÉER:" -ForegroundColor Yellow
Write-Host "==================" -ForegroundColor Yellow
Write-Host "👨‍👩‍👧‍👦 PARTICULIERS: 2 comptes (Famille Diallo, Ahmadou Ba)" -ForegroundColor Cyan
Write-Host "🏠 VENDEURS: 2 comptes (Héritage Fall, Domaine Seck)" -ForegroundColor Cyan
Write-Host "🏗️  PROMOTEURS: 2 comptes (Urban Developers, Sahel Construction)" -ForegroundColor Cyan
Write-Host "🏦 BANQUES: 2 comptes (BOA Sénégal, Crédit Agricole)" -ForegroundColor Cyan
Write-Host "📝 NOTAIRES: 2 comptes (Étude Diouf, Chambre des Notaires)" -ForegroundColor Cyan
Write-Host "🏢 AGENTS FONCIERS: 2 comptes (Foncier Expert, Teranga Immobilier)" -ForegroundColor Cyan
Write-Host ""
Write-Host "🎯 TOTAL: 12 nouveaux comptes" -ForegroundColor Green
Write-Host "🔑 Mot de passe: password123" -ForegroundColor Yellow
Write-Host ""
Write-Host "▶️  PROCHAINE ÉTAPE:" -ForegroundColor Yellow
Write-Host "   Exécutez le fichier create-remaining-accounts.sql sur Supabase" -ForegroundColor White