
import { 
  LayoutDashboard, 
  Users, 
  UserCheck, 
  FileText, 
  MapPin, 
  Settings, 
  BarChart, 
  FileSignature, 
  FileCheck as FileCheckIcon, 
  LifeBuoy, 
  UploadCloud, 
  Building, 
  LandPlot, 
  Heart, 
  Bell, 
  Banknote, 
  TrendingUp, 
  Leaf, 
  Briefcase, 
  ChevronDown, 
  ChevronRight, 
  MessageSquare, 
  Home, 
  Blocks,
  ShieldQuestion, 
  AlertTriangle, 
  Map, 
  Gavel,
  Trees
} from 'lucide-react';

    export const getSidebarConfig = (user) => {
      if (!user) return [];

      const roleConfigs = {
        'Admin': [
          { isHeader: true, label: '📊 Administration' },
          { href: '/admin', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
          { href: '/analytics', label: 'Analytics', icon: BarChart },
          { href: '/admin/reports', label: 'Rapports', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '👥 Gestion Utilisateurs' },
          {
            label: 'Gestion des Acteurs',
            icon: Users,
            subItems: [
              { href: '/admin/users', label: 'Tous les acteurs', icon: Users },
              { href: '/admin/user-verifications', label: 'Vérifications', icon: UserCheck },
              { href: '/admin/user-requests', label: 'Demandes de rôle', icon: ShieldQuestion },
            ]
          },
          { isSeparator: true },
          { isHeader: true, label: '📝 Gestion Contenus' },
          {
            label: 'Contenus & Annonces',
            icon: FileText,
            subItems: [
              { href: '/admin/parcels', label: 'Annonces de parcelles', icon: MapPin },
              { href: '/admin/system-requests', label: 'Soumissions de parcelles', icon: UploadCloud },
              { href: '/admin/blog', label: 'Blog', icon: FileSignature },
            ]
          },
          { isSeparator: true },
          { isHeader: true, label: '🔧 Système' },
          { href: '/admin/audit-log', label: 'Journal d\'audit', icon: FileCheckIcon },
          { href: '/admin/settings', label: 'Paramètres Système', icon: Settings },
        ],
        'Particulier': [
          { isHeader: true, label: '📊 Tableau de Bord' },
          { href: '/acheteur', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
          { href: '/my-requests', label: 'Mes Demandes', icon: FileText },
          { href: '/transactions', label: 'Mes Transactions', icon: TrendingUp },
          { href: '/favorites', label: 'Mes Favoris', icon: Heart },
          { isSeparator: true },
          { isHeader: true, label: '🏠 Marché Immobilier' },
          { href: '/parcelles-vendeurs', label: 'Parcelles Privées', icon: MapPin },
          { href: '/communal-zones', label: 'Zones Communales', icon: Leaf },
          { href: '/promoters-projects', label: 'Projets Immobiliers', icon: Building },
          { href: '/request-municipal-land', label: 'Terrain Communal', icon: Trees },
          { isSeparator: true },
          { isHeader: true, label: '🔧 Outils & Services' },
          { href: '/solutions/construction-request', label: 'Construction', icon: Home },
          { href: '/buyer/financing', label: 'Financement', icon: Banknote },
          { href: '/tools/price-calculator', label: 'Calculateur Prix', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '💬 Communication' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Mon Compte', icon: Settings },
        ],
        'Vendeur Particulier': [
          { isHeader: true, label: '📊 Mon Business' },
          { href: '/dashboard/vendeur', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
          { href: '/dashboard/my-listings', label: 'Mes Annonces', icon: MapPin },
          { href: '/dashboard/transactions', label: 'Mes Ventes', icon: Banknote },
          { href: '/dashboard/analytics', label: 'Performances', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '📝 Gestion' },
          { href: '/dashboard/add-parcel', label: 'Ajouter un bien', icon: UploadCloud },
          { href: '/dashboard/my-requests', label: 'Demandes Reçues', icon: FileText },
          { isSeparator: true },
          { isHeader: true, label: '💬 Communication' },
          { href: '/dashboard/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/dashboard/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/dashboard/settings', label: 'Mon Compte', icon: Settings },
        ],
        // Alias pour le rôle vendeur simple
        'vendeur': [
          { isHeader: true, label: 'Espace Vendeur' },
          { href: '/dashboard/vendeur', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/my-listings', label: 'Mes Annonces', icon: MapPin },
          { href: '/dashboard/add-parcel', label: 'Ajouter un bien', icon: UploadCloud },
          { href: '/dashboard/my-requests', label: 'Demandes Reçues', icon: FileText },
          { href: '/dashboard/transactions', label: 'Transactions', icon: Banknote },
          { href: '/dashboard/analytics', label: 'Analyse d\'Audience', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/dashboard/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/dashboard/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/dashboard/settings', label: 'Paramètres', icon: Settings },
        ],
        'Vendeur Pro': [
          { isHeader: true, label: 'Espace Vendeur Pro' },
          { href: '/dashboard/vendeur', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/my-listings', label: 'Mes Annonces', icon: MapPin },
          { href: '/dashboard/add-parcel', label: 'Ajouter un bien', icon: UploadCloud },
          { href: '/dashboard/my-requests', label: 'Demandes Reçues', icon: FileText },
          { href: '/dashboard/transactions', label: 'Transactions', icon: Banknote },
          { href: '/dashboard/analytics', label: 'Analyse d\'Audience', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/dashboard/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/dashboard/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/dashboard/settings', label: 'Paramètres', icon: Settings },
        ],
        'Mairie': [
          { isHeader: true, label: 'Gestion Communale' },
          { href: '/solutions/mairies/dashboard', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
          { href: '/dashboard/mairie-requests', label: 'Demandes', icon: FileSignature },
          { href: '/dashboard/land-management', label: 'Gestion Foncière', icon: LandPlot },
          { href: '/dashboard/cadastre', label: 'Cadastre Numérique', icon: Map },
          { href: '/dashboard/disputes', label: 'Gestion des Litiges', icon: AlertTriangle },
          { href: '/dashboard/urban-plan', label: 'Plan d\'Urbanisme', icon: Building },
          { href: '/dashboard/mairie-reports', label: 'Rapports & Stats', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Agent Foncier': [
          { isHeader: true, label: 'Espace Agent' },
          { href: '/agent', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/agent/tasks', label: 'Mes Tâches', icon: FileCheckIcon },
          { href: '/agent/parcels', label: 'Parcelles Suivies', icon: MapPin },
          { href: '/agent/clients', label: 'Mes Clients', icon: Users },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Investisseur': [
          { isHeader: true, label: 'Espace Investisseur' },
          { href: '/solutions/investisseurs/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/opportunities', label: 'Opportunités', icon: TrendingUp },
          { href: '/dashboard/investments', label: 'Mes Investissements', icon: Briefcase },
          { href: '/dashboard/market-analysis', label: 'Analyse de Marché', icon: BarChart },
          { href: '/dashboard/due-diligence', label: 'Due Diligence', icon: FileCheckIcon },
          { href: '/dashboard/roi-calculator', label: 'Calculateur ROI', icon: Banknote },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Promoteur': [
          { isHeader: true, label: 'Espace Promoteur' },
          { href: '/solutions/promoteurs/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/projects', label: 'Mes Projets', icon: Building },
          { href: '/dashboard/construction-tracking', label: 'Suivi de Chantier', icon: MapPin },
          { href: '/dashboard/sales', label: 'Ventes', icon: Banknote },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Agriculteur': [
          { isHeader: true, label: 'Espace Agriculteur' },
          { href: '/solutions/agriculteurs/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/my-lands', label: 'Mes Terres', icon: LandPlot },
          { href: '/dashboard/logbook', label: 'Journal de Culture', icon: FileSignature },
          { href: '/dashboard/soil-analysis', label: 'Analyse de Sol', icon: FileCheckIcon },
          { href: '/dashboard/weather', label: 'Météo Agricole', icon: Leaf },
          { href: '/dashboard/equipment', label: 'Matériel', icon: Briefcase },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Banque': [
          { isHeader: true, label: 'Espace Banque' },
          { href: '/solutions/banques/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/funding-requests', label: 'Demandes de Financement', icon: Banknote },
          { href: '/dashboard/guarantees', label: 'Garanties', icon: FileSignature },
          { href: '/dashboard/land-valuation', label: 'Évaluation Foncière', icon: MapPin },
          { href: '/dashboard/compliance', label: 'Conformité', icon: FileCheckIcon },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Notaire': [
          { isHeader: true, label: 'Espace Notaire' },
          { href: '/solutions/notaires/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/cases', label: 'Dossiers en Cours', icon: Briefcase },
          { href: '/dashboard/authentication', label: 'Authentification d\'Actes', icon: FileSignature },
          { href: '/dashboard/archives', label: 'Archives Numériques', icon: FileText },
          { href: '/dashboard/compliance-check', label: 'Vérification Conformité', icon: FileCheckIcon },
          { isSeparator: true },
          { isHeader: true, label: 'Interactions' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          { isSeparator: true },
          { isHeader: true, label: 'Mon Compte' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
      };

      const baseConfig = [
        { href: '/dashboard', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
        { href: '/settings', label: 'Paramètres', icon: Settings },
      ];

      return roleConfigs[user.role] || baseConfig;
    };
