import { 
  LayoutDashboard, 
  Users, 
  UserCheck, 
  FileText, 
  MapPin, 
  Settings, 
  BarChart, 
  FileSignature, 
  FileCheck as FileCheckIcon, 
  LifeBuoy, 
  UploadCloud, 
  Building, 
  LandPlot, 
  Heart, 
  Bell, 
  Banknote, 
  TrendingUp, 
  Leaf, 
  Briefcase, 
  ChevronDown, 
  ChevronRight, 
  MessageSquare, 
  Home, 
  Blocks,
  ShieldQuestion, 
  AlertTriangle, 
  Map, 
  Gavel,
  Trees,
  ShieldCheck,
  FileSearch,
  History,
  Award,
  Shield,
  Lock,
  Wallet,
  Activity,
  Brain,
  Zap,
  Eye,
  Clock,
  Calendar,
  CreditCard
} from 'lucide-react';

    export const getSidebarConfig = (user) => {
      if (!user) return [];

      const roleConfigs = {
        'Admin': [
          { isHeader: true, label: '📊 Administration' },
          { href: '/admin', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
          { href: '/analytics', label: 'Analytics', icon: BarChart },
          { href: '/admin/reports', label: 'Rapports', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '👥 Gestion Utilisateurs' },
          {
            label: 'Gestion des Acteurs',
            icon: Users,
            subItems: [
              { href: '/admin/users', label: 'Tous les acteurs', icon: Users },
              { href: '/admin/user-verifications', label: 'Vérifications', icon: UserCheck },
              { href: '/admin/user-requests', label: 'Demandes de rôle', icon: ShieldQuestion },
            ]
          },
          { isSeparator: true },
          { isHeader: true, label: '📄 Gestion Contenus' },
          {
            label: 'Contenus & Annonces',
            icon: FileText,
            subItems: [
              { href: '/admin/parcels', label: 'Annonces de parcelles', icon: MapPin },
              { href: '/admin/system-requests', label: 'Soumissions de parcelles', icon: UploadCloud },
              { href: '/admin/blog', label: 'Blog', icon: FileSignature },
            ]
          },
          { isSeparator: true },
          { isHeader: true, label: '🔧 Système' },
          { href: '/admin/audit-log', label: 'Journal d\'audit', icon: FileCheckIcon },
          { href: '/admin/settings', label: 'Paramètres Système', icon: Settings },
        ],
        'Particulier': [
          { isHeader: true, label: '📊 Tableau de Bord' },
          { href: '/dashboard/acheteur', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
          
          { isSeparator: true },
          { isHeader: true, label: '📋 Suivi de mes Dossiers' },
          { href: '/dashboard/acheteur/private-interests', label: 'Intérêts Terrains Privés', icon: MapPin },
          { href: '/dashboard/acheteur/municipal-applications', label: 'Demandes Communales', icon: Building },
          { href: '/dashboard/acheteur/promoter-reservations', label: 'Réservations VEFA', icon: Home },
          
          { isSeparator: true },
          { isHeader: true, label: '💰 Suivi Financier' },
          { href: '/dashboard/acheteur/payment-schedules', label: 'Échéanciers Paiements', icon: Calendar },
          { href: '/dashboard/acheteur/bank-applications', label: 'Dossiers Bancaires', icon: Banknote },
          { href: '/dashboard/acheteur/transaction-history', label: 'Historique Transactions', icon: History },
          
          { isSeparator: true },
          { isHeader: true, label: '🔗 Mes Propriétés Blockchain' },
          { href: '/dashboard/acheteur/owned-properties', label: 'Propriétés Acquises', icon: Award },
          { href: '/dashboard/acheteur/active-contracts', label: 'Contrats en Cours', icon: Shield },
          { href: '/dashboard/acheteur/escrow-status', label: 'Dépôts Sécurisés', icon: Lock },
          
          { isSeparator: true },
          { isHeader: true, label: '📂 Documents & RDV' },
          { href: '/dashboard/acheteur/my-documents', label: 'Centre Documents', icon: FileText },
          { href: '/dashboard/acheteur/scheduled-visits', label: 'Visites Programmées', icon: Eye },
          { href: '/dashboard/acheteur/appointments', label: 'Rendez-vous', icon: Clock },
          
          { isSeparator: true },
          { isHeader: true, label: '💬 Communication' },
          { href: '/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/notifications', label: 'Notifications', icon: Bell },
          
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Mon Compte', icon: Settings },
        ],
        'Vendeur Particulier': [
          { isHeader: true, label: '📊 Mon Business' },
          { href: '/dashboard/vendeur', label: 'Vue d\'ensemble', icon: LayoutDashboard, end: true },
          { href: '/dashboard/my-listings', label: 'Mes Annonces', icon: MapPin },
          { href: '/dashboard/transactions', label: 'Mes Ventes', icon: Banknote },
          { href: '/dashboard/analytics', label: 'Performances', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '📝 Gestion' },
          { href: '/dashboard/add-parcel', label: 'Ajouter un bien', icon: UploadCloud },
          { href: '/dashboard/my-requests', label: 'Demandes Reçues', icon: FileText },
          { isSeparator: true },
          { isHeader: true, label: '💬 Communication' },
          { href: '/dashboard/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/dashboard/vendeur/reviews', label: 'Mes Avis', icon: Award },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Vendeur': [
          { isHeader: true, label: '📊 Mon Business' },
          { href: '/dashboard/vendeur', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/dashboard/my-listings', label: 'Mes Annonces', icon: MapPin },
          { href: '/dashboard/transactions', label: 'Mes Ventes', icon: Banknote },
          { href: '/dashboard/analytics', label: 'Performances', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '📝 Gestion' },
          { href: '/dashboard/add-parcel', label: 'Ajouter un bien', icon: UploadCloud },
          { href: '/dashboard/my-requests', label: 'Demandes Reçues', icon: FileText },
          { isSeparator: true },
          { isHeader: true, label: '💬 Communication' },
          { href: '/dashboard/messaging', label: 'Messagerie', icon: MessageSquare },
          { href: '/dashboard/vendeur/reviews', label: 'Mes Avis', icon: Award },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Investisseur': [
          { isHeader: true, label: '📊 Investissements' },
          { href: '/solutions/investisseurs/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/solutions/investisseurs/portfolio', label: 'Mon Portfolio', icon: Award },
          { href: '/solutions/investisseurs/analytics', label: 'Analyses', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '🎯 Opportunités' },
          { href: '/solutions/investisseurs/opportunities', label: 'Nouvelles Opportunités', icon: TrendingUp },
          { href: '/solutions/investisseurs/watchlist', label: 'Ma Watchlist', icon: Eye },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Promoteur': [
          { isHeader: true, label: '📊 Mes Projets' },
          { href: '/solutions/promoteurs/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/solutions/promoteurs/projects', label: 'Projets en cours', icon: Building },
          { href: '/solutions/promoteurs/analytics', label: 'Analyses', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '🚧 Construction' },
          { href: '/solutions/promoteurs/construction-requests', label: 'Demandes de Construction', icon: Gavel },
          { href: '/solutions/promoteurs/progress', label: 'Suivi Avancement', icon: Activity },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Agriculteur': [
          { isHeader: true, label: '🌾 Mes Terrains Agricoles' },
          { href: '/solutions/agriculteurs/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/solutions/agriculteurs/lands', label: 'Mes Terres', icon: Trees },
          { href: '/solutions/agriculteurs/analytics', label: 'Analyses', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '📊 Gestion' },
          { href: '/solutions/agriculteurs/production', label: 'Suivi Production', icon: Leaf },
          { href: '/solutions/agriculteurs/requests', label: 'Demandes Terrain', icon: FileText },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Banque': [
          { isHeader: true, label: '🏦 Mon Interface Bancaire' },
          { href: '/solutions/banques/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/solutions/banques/guarantees', label: 'Évaluation Garanties', icon: Shield },
          { href: '/solutions/banques/analytics', label: 'Analyses Risques', icon: BarChart },
          { isSeparator: true },
          { isHeader: true, label: '📊 Portefeuille' },
          { href: '/solutions/banques/portfolio', label: 'Portfolio Immobilier', icon: Building },
          { href: '/solutions/banques/applications', label: 'Demandes Crédit', icon: FileText },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Notaire': [
          { isHeader: true, label: '⚖️ Mon Office Notarial' },
          { href: '/solutions/notaires/dashboard', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/solutions/notaires/contracts', label: 'Contrats & Actes', icon: FileText },
          { href: '/solutions/notaires/verifications', label: 'Vérifications Légales', icon: ShieldCheck },
          { isSeparator: true },
          { isHeader: true, label: '📋 Dossiers' },
          { href: '/solutions/notaires/pending', label: 'Dossiers en Cours', icon: Clock },
          { href: '/solutions/notaires/completed', label: 'Dossiers Finalisés', icon: Award },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ],
        'Agent Foncier': [
          { isHeader: true, label: '🏘️ Mon Agence' },
          { href: '/agent', label: 'Tableau de Bord', icon: LayoutDashboard, end: true },
          { href: '/agent/listings', label: 'Mes Annonces', icon: MapPin },
          { href: '/agent/clients', label: 'Mes Clients', icon: Users },
          { href: '/agent/transactions', label: 'Mes Transactions', icon: Banknote },
          { isSeparator: true },
          { isHeader: true, label: '📊 Performance' },
          { href: '/agent/analytics', label: 'Analyses', icon: BarChart },
          { href: '/agent/commissions', label: 'Commissions', icon: TrendingUp },
          { isSeparator: true },
          { isHeader: true, label: '⚙️ Paramètres' },
          { href: '/settings', label: 'Paramètres', icon: Settings },
        ]
      };

      const role = user.role || user.user_type || '';
      return roleConfigs[role] || roleConfigs['Particulier'];
    };